name: "random_forest"
class_path: "sklearn.ensemble.RandomForestRegressor"
params:
  random_state: ${seed}
  n_jobs: -1
search_space:
  n_estimators:
    type: "choice"
    values: [100, 200, 500]
  max_depth:
    type: "choice"
    values: [10, 20, 30, null]
  min_samples_split:
    type: "randint"
    lower: 2
    upper: 20
  min_samples_leaf:
    type: "randint" 
    lower: 1
    upper: 10
  max_features:
    type: "choice"
    values: ["sqrt", "log2", null]
