data_version: "1.0.0"

# Parameters for Nextflow pipeline
data_version: "1.0.0"
preprocessing: [basic, minmax_pipeline, kbest_standard]
models: [xgboost, random_forest, linear]
search: [bayesian, random]

# Runtime configuration
run_mode: hpc  # 'local' or 'hpc'
local_config:
  cpus: 2
  memory: 8.GB
  time: 30.m
  max_experiments: 2  # Limit for local testing
hpc_config:
  cpus_xgboost: 4
  cpus_other: 8
  memory: 32.GB
  time_xgboost: 2.h
  time_other: 4.h
