name: "bayesian"
algorithm: "tpe"  # Tree-structured Parzen Estimator (Optuna's default)
n_trials: 100
params:
  # Additional Optuna-specific parameters can go here
  n_startup_trials: 10  # Random trials before TPE kicks in
  n_ei_candidates: 24   # Number of candidates for expected improvement
